= Epsilon-Raspberry

This repo contains config files for the primary and secondary pi.


== File Information

The `xorg.conf` tells the Xserver how to layout the video output from the pi onto the screen. 
This file is only needed on the primary pi.
The `xorg.conf` file should be placed in `/etc/X11/`.

The `config.txt` file is the equivalent of a BIOS on the pi. It contains system configuration parameters. 
This file is needed on the primary and secondary pi.
The `config.txt` file should be placed in `/boot/`.

= Instructions to run SetupScript

Ensure to clone Repo to home directory (~) in order for the script to know where to move patch files upon running of the script.
----
cd ~
git clone https://github.com/UCSolarCarTeam/Epsilon-Raspberry.git
----
Navigate to Epsilon-Raspberry Directory.
----
cd Epsilon-Raspberry
----
Before running the setup script, make sure that:

* You have consistent, stable internet connection.
* You won't need to use the pi or move your computer until the script is complete.
The script may take several *hours* to run, so be prepared to leave your computer on all night.
----
./SetupScript
----
Flash forward to after completion, CONGRATULATIONS you are almost there, I believe in you.
Navigate to your .bashrc file in your home (~/) directory and add the following two lines:
----
export LD_LIBRARY_PATH=/usr/local/Qt-5.5.1/lib/:/usr/local/lib
export PATH=/usr/local/Qt-5.5.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local
----
Save the changes and source the file to initialize the changes.
----
source ~/.bashrc
----
Then check where it points, should be `/usr/local/Qt-5.5.1/bin/qmake`
----
which qmake
----
You should be good to compile sample applications and run them now!
