= Epsilon-Raspberry

This repository contains config files and setup scripts for the Primary and Secondary pi.


== File Information

The `xorg.conf` tells the Xserver how to layout the video output from the pi onto the screen. 
This file is only needed on the primary pi.
The `xorg.conf` file should be placed in `/etc/X11/`.

The `config.txt` file is the equivalent of a BIOS on the pi. It contains system configuration parameters. 
This file is needed on the primary and secondary pi.
The `config.txt` file should be placed in `/boot/`.

The `rabbitmq.config` file is needed for communication between the two pis.
This file is should be placed in `/etc/rabbitmq/`

The `.desktop` files will be run on startup. 
It will run the startup scripts to run domovoi.
These files should be placed in `/home/pi/.config/autostart/`

= Setting Up Cross Compilation

See the https://github.com/UCSolarCarTeam/Epsilon-Raspberry/blob/master/cross-compile/README.adoc[cross compilation setup guide] for instructions on how to setup cross compilation.

= Ways to Interface with the Pi

* Manually with a screen, keyboard, and mouse.
* `ssh` - opens a terminal to the pi through a local network (such as a mobile hotspot, no data needed)
* `vnc` - Opens a remote desktop connection to the Pi, showing the contents of the screen.

== Login Information
* Primary Pi Username: `primarypi.local`
* Secondary Pi Username: `secondarypi.local`
* Contact the software manager for the pi passwords 

= Running Programs on Startup

The `Startup.sh` scripts are currently set to run from `~/.profile`.

A current limitation of this is that on the primary pi, Xinerama will consider the two screens as two "logins", and execute the `~/.profile` commands twice.